/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    RegisterForm: typeof import('./src/components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideTools: typeof import('./src/components/SideTools.vue')['default']
  }
}
